/**
 * ============================================================
 *  BUNOFEED — Products & Campaign Data  (products.js)
 *  Auto-generated by Bunofeed Admin Panel
 *  Last updated: 30/5/2026, 12:26:52 pm
 * ============================================================
 */

window.BUNOFEED_DATA = {
  "payment": {
    "razorpayKeyId": "rzp_test_SntAL1SqrD5Bht",
    "currency": "INR",
    "businessName": "Bunofeed",
    "description": "Healthy Natural Foods",
    "logoUrl": "https://bunofeed.in/images/logo2.png",
    "themeColor": "#ff6b00"
  },
  "campaign": {
    "active": false,
    "text": "🎉 Launch Special — Free shipping on orders above ₹499!",
    "link": "shop.html",
    "linkText": "Shop Now →",
    "bgColor": "#ff6b00",
    "textColor": "#ffffff",
    "expiryDate": "2026-06-30"
  },
  "sale": {
    "active": false,
    "discountPercent": 15,
    "label": "SALE",
    "endDate": "2026-05-31"
  },
  "shipping": {
    "freeShippingAbove": 499,
    "serviceablePincodes": [
      "243201",
      "243202"
    ]
  },
  "coupons": [
    {
      "code": "BUNO10",
      "discountType": "percent",
      "discountValue": 10,
      "scope": "all",
      "productId": ""
    },
    {
      "code": "CRUNCHY20",
      "discountType": "percent",
      "discountValue": 20,
      "scope": "specific",
      "productId": "creamy-pb"
    }
  ],
  "products": [
    {
      "id": "creamy-pb",
      "name": "Classic Peanut Butter Smooth",
      "tagline": "Creamy, Protein-Rich Peanut Butter Made from Roasted Peanuts",
      "description": "Enjoy the rich taste and smooth texture of Classic Peanut Butter Smooth, crafted from carefully selected roasted peanuts. This creamy spread is a delicious source of plant-based protein and healthy fats, making it a perfect addition to breakfast, snacks, smoothies, and fitness-focused diets. Its smooth consistency spreads easily on bread, toast, crackers, and can also be used in shakes, desserts, and recipes. Whether you're an athlete, fitness enthusiast, or simply looking for a nutritious everyday spread, Classic Peanut Butter Smooth delivers great taste and wholesome nutrition in every spoonful.",
      "price": 299,
      "mrp": 399,
      "weight": "400g",
      "allowedSizes": [
        "400g"
      ],
      "allowedTextures": [
        "Smooth",
        "Crunchy"
      ],
      "pricing": {
        "Smooth_400g": {
          "basePrice": 115.2,
          "profit": 0,
          "discount": 10,
          "gst": 5
        },
        "Crunchy_400g": {
          "basePrice": 115.2,
          "profit": 0,
          "discount": 10,
          "gst": 5
        }
      },
      "image": "https://bunofeed.in/images/Classic Smooth/1_front.png",
      "images": [
        "https://bunofeed.in/images/Classic Smooth/1_front.png",
        "https://bunofeed.in/images/Classic Smooth/2_back.png",
        "https://bunofeed.in/images/Classic Smooth/3_classic_smooth.png",
        "https://bunofeed.in/images/Classic Smooth/4_classic_smooth.png",
        "https://bunofeed.in/images/Classic Smooth/5_classic_smooth.png",
        "https://bunofeed.in/images/Classic Smooth/6_classic_smooth.png",
        "https://bunofeed.in/images/Classic Smooth/7.png"
      ],
      "emoji": "🥜",
      "badge": "Limited Stock",
      "badgeType": "limited",
      "bgClass": "peanut-bg",
      "category": "peanut-butter",
      "features": [
        "High Protein",
        "Made from Roasted Peanuts",
        "Rich in Healthy Fats",
        "No Trans Fat",
        "Vegetarian Perfect for Breakfast"
      ],
      "ingredients": "Roasted Peanut (87.5%), Dhaga Mishri (10%), Pink Salt",
      "keyBenefits": "Good source of plant-based protein.\nProvides long-lasting energy.\nRich in healthy unsaturated fats.\nHelps support an active lifestyle.\nSmooth texture makes spreading easy.\nSuitable for sandwiches, smoothies, baking, and snacking.\nContains naturally occurring nutrients from peanuts.\nConvenient and versatile everyday food option.",
      "storageInfo": "Store in a cool, dry place away from direct sunlight.\nKeep the lid tightly closed after use.\nStir before use if natural oil separation occurs.\nRefrigeration is optional but may help maintain freshness after opening.\nSHELF LIFE:  24 Months from date of mfg.",
      "allergenInfo": "Contains Peanuts.\nManufactured in a facility that may also process tree nuts, milk, soy, wheat, and sesame products.",
      "hsnCode": "1234",
      "visible": true,
      "bestSeller": true
    }
  ],
  "hero": {
    "subtitle": "Welcome to Bunofeed",
    "title": "Companion in your",
    "titleHighlight": "Healthy Lifestyle",
    "description": "Fuel your body with nature's finest — real, healthy food products. No nasties. Just goodness.",
    "ctaText": "Shop Now",
    "ctaLink": "shop.html"
  },
  "brand": {
    "email": "bunofeedhelpdesk@gmail.com",
    "feedbackFormUrl": "https://docs.google.com/forms/d/e/1FAIpQLSejJAsyZq1snX9gEJr6CTpcVYwEopd34RsTf_pbYvgwz0WFDg/viewform?usp=header",
    "instagram": "https://www.instagram.com",
    "facebook": "https://www.facebook.com",
    "linkedin": "https://www.linkedin.com/in/akash-kumar-995739293"
  },
  "categories": [
    {
      "name": "Peanut Butter",
      "slug": "peanut-butter"
    },
    {
      "name": "Oats",
      "slug": "oats"
    },
    {
      "name": "Muesli",
      "slug": "muesli"
    },
    {
      "name": "Other",
      "slug": "other"
    }
  ]
};
