/**
 * ============================================================
 *  BUNOFEED — Products & Campaign Data  (products.js)
 *  Auto-generated by Bunofeed Admin Panel
 *  Last updated: 29/5/2026, 8:00:53 am
 *
 *  SHIPPING MATRIX GUIDE (for Admin Panel)
 *  ─────────────────────────────────────────
 *  Rules in shippingMatrix are checked top-to-bottom.
 *  First matching rule wins.
 *
 *  Each rule has:
 *    pincodes  — comma-separated list OR "*" for all
 *    packSize  — e.g. "400g", "500g", "900g" OR "*" for all
 *    charge    — shipping fee in ₹ (0 = free)
 *
 *  Examples:
 *    Free for serviceable pincodes on any pack:
 *      { pincodes: "243201,243202", packSize: "*", charge: 0 }
 *
 *    ₹49 for 900g to all pincodes:
 *      { pincodes: "*", packSize: "900g", charge: 49 }
 *
 *    ₹39 for all other orders:
 *      { pincodes: "*", packSize: "*", charge: 39 }
 *
 *  If no rule matches, freeShippingAbove threshold is used.
 *  If order total >= freeShippingAbove → Free, else flatShippingCharge.
 * ============================================================
 */

window.BUNOFEED_DATA = {
  "payment": {
    "razorpayKeyId": "rzp_test_SntAL1SqrD5Bht",
    "currency": "INR",
    "businessName": "Bunofeed",
    "description": "Healthy Natural Foods",
    "logoUrl": "https://bunofeed.in/images/logo2.png",
    "themeColor": "#ff6b00"
  },
  "campaign": {
    "active": false,
    "text": "🎉 Launch Special — Free shipping on orders above ₹499!",
    "link": "shop.html",
    "linkText": "Shop Now →",
    "bgColor": "#ff6b00",
    "textColor": "#ffffff",
    "expiryDate": "2026-06-30"
  },
  "sale": {
    "active": false,
    "discountPercent": 15,
    "label": "SALE",
    "endDate": "2026-05-31"
  },
  "shipping": {
    "freeShippingAbove": 499,
    "flatShippingCharge": 49,
    /*
     * ── SHIPPING MATRIX ─────────────────────────────────────
     * Add / edit rules here (or via the admin panel).
     * Rules are matched top-to-bottom; first match wins.
     *
     * Current setup: free shipping to serviceable pincodes,
     * ₹49 flat for all other valid pincodes.
     * ─────────────────────────────────────────────────────── */
    "shippingMatrix": [
      {
        "pincodes": "243201,243202",
        "packSize": "*",
        "charge": 0
      },
      {
        "pincodes": "*",
        "packSize": "*",
        "charge": 49
      }
    ]
  },
  "serviceablePincodes": [
    "243201",
    "243202"
  ],
  "coupons": [
    {
      "code": "BUNO10",
      "discountType": "percent",
      "discountValue": 10,
      "scope": "all",
      "productId": ""
    },
    {
      "code": "CRUNCHY20",
      "discountType": "percent",
      "discountValue": 20,
      "scope": "specific",
      "productId": "creamy-pb"
    }
  ],
  "products": [
    {
      "id": "creamy-pb",
      "name": "Classic Peanut Butter",
      "tagline": "Tasty & packed with protein.",
      "description": "BUNOFEED Classic Peanut Butter is made from premium quality roasted peanuts to give you the perfect balance of rich taste, smooth texture, and natural nutrition. Packed with protein and healthy fats, it is an ideal choice for fitness lovers, busy mornings, and healthy snacking.\n\nSpread it on bread, add it to smoothies, drizzle over oats, or enjoy it straight from the jar — every spoon delivers delicious peanut goodness with a satisfying roasted flavor.\n\n• Rich in Protein\n• Smooth & Creamy Texture\n• Made from Quality Roasted Peanuts\n• Perfect for Breakfast & Snacks\n• No Compromise on Taste\n\nFuel your day the delicious way with BUNOFEED Classic Peanut Butter.",
      "price": 299,
      "mrp": 399,
      "weight": "400g",
      "allowedSizes": [
        "400g"
      ],
      "allowedTextures": [
        "Smooth",
        "Crunchy"
      ],
      "pricing": {
        "Smooth_400g": {
          "basePrice": 115.2,
          "profit": 0,
          "discount": 10,
          "gst": 5
        },
        "Smooth_500g": {
          "basePrice": 220,
          "profit": 0,
          "discount": 0,
          "gst": 18
        },
        "Smooth_900g": {
          "basePrice": 380,
          "profit": 0,
          "discount": 10,
          "gst": 18
        },
        "Crunchy_400g": {
          "basePrice": 144,
          "profit": 0,
          "discount": 10,
          "gst": 5
        },
        "Crunchy_500g": {
          "basePrice": 230,
          "profit": 0,
          "discount": 10,
          "gst": 18
        },
        "Crunchy_900g": {
          "basePrice": 390,
          "profit": 0,
          "discount": 10,
          "gst": 18
        },
        "Crispy_400g": {
          "basePrice": 195,
          "profit": 0,
          "discount": 10,
          "gst": 18
        },
        "Crispy_500g": {
          "basePrice": 235,
          "profit": 0,
          "discount": 10,
          "gst": 18
        },
        "Crispy_900g": {
          "basePrice": 395,
          "profit": 0,
          "discount": 10,
          "gst": 18
        }
      },
      "image": "https://i.ibb.co/psxqc3J/1-removebg-preview.png",
      "images": [
        "https://i.ibb.co/psxqc3J/1-removebg-preview.png",
        "https://i.ibb.co/SDG4SYSN/1.png"
      ],
      "emoji": "🥜",
      "badge": "Best Seller",
      "badgeType": "bestseller",
      "bgClass": "peanut-bg",
      "category": "peanut-butter",
      "features": [
        "High Protein",
        "No Palm Oil",
        "Vegan"
      ],
      "ingredients": "Roasted Peanuts (95%), Dark Cocoa Powder (4%), Salt (1%). No added sugar, no palm oil, no preservatives.",
      "keyBenefits": "Rich source of plant-based protein • Contains healthy monounsaturated fats • No palm oil or artificial preservatives • Antioxidant-rich dark cocoa • Suitable for pre/post-workout nutrition",
      "storageInfo": "Store in a cool, dry place away from direct sunlight. Keep lid tightly closed after opening. Best consumed within 3 months of opening. No refrigeration required.",
      "allergenInfo": "Contains Peanuts.",
      "hsnCode": "1234",
      "visible": true,
      "bestSeller": true
    }
  ],
  "hero": {
    "subtitle": "Welcome to Bunofeed",
    "title": "Companion in your",
    "titleHighlight": "Healthy Lifestyle",
    "description": "Fuel your body with nature's finest — real, healthy food products. No nasties. Just goodness.",
    "ctaText": "Shop Now",
    "ctaLink": "shop.html"
  },
  "brand": {
    "email": "bunofeedhelpdesk@gmail.com",
    "feedbackFormUrl": "https://docs.google.com/forms/d/e/1FAIpQLSejJAsyZq1snX9gEJr6CTpcVYwEopd34RsTf_pbYvgwz0WFDg/viewform?usp=header",
    "instagram": "https://www.instagram.com",
    "facebook": "https://www.facebook.com",
    "linkedin": "https://www.linkedin.com/in/akash-kumar-995739293"
  },
  "categories": [
    {
      "name": "Peanut Butter",
      "slug": "peanut-butter"
    },
    {
      "name": "Oats",
      "slug": "oats"
    },
    {
      "name": "Muesli",
      "slug": "muesli"
    },
    {
      "name": "Other",
      "slug": "other"
    }
  ]
};
