/**
 * ============================================================
 *  BUNOFEED — Products & Campaign Data  (products.js)
 *  Auto-generated by Bunofeed Admin Panel
 *  Last updated: 23/5/2026, 10:21:52 pm
 * ============================================================
 */

window.BUNOFEED_DATA = {
  "payment": {
    "razorpayKeyId": "rzp_test_SntAL1SqrD5Bht",
    "currency": "INR",
    "businessName": "Bunofeed",
    "description": "Healthy Natural Foods",
    "logoUrl": "https://bunofeed.in/images/logo2.png",
    "themeColor": "#ff6b00"
  },
  "campaign": {
    "active": false,
    "text": "🎉 Launch Special — Free shipping on orders above ₹499!",
    "link": "shop.html",
    "linkText": "Shop Now →",
    "bgColor": "#ff6b00",
    "textColor": "#ffffff",
    "expiryDate": "2026-06-30"
  },
  "sale": {
    "active": false,
    "discountPercent": 15,
    "label": "SALE",
    "endDate": "2026-05-31"
  },
  "shipping": {
    "freeShippingAbove": 499,
    "shippingCharge": 50
  },
  "serviceablePincodes": [
    "243201",
    "243202"
  ],
  "pincodeShipping": {
    "243201": 50,
    "243202": 40
  },
  "products": [
    {
      "id": "creamy-pb",
      "name": "Dark Chocolate Peanut Butter",
      "tagline": "Tasty, Crunchy & packed with protein.",
      "description": "Indulgent dark chocolate meets creamy roasted peanuts in a perfectly smooth spread crafted for taste and nutrition. Made with high-quality peanuts and rich cocoa, this protein-packed peanut butter delivers a deep chocolate flavor without compromising on wholesome ingredients.\nPerfect for:\n\nToasts & sandwiches\nSmoothies & shakes\nFruits & pancakes\nPre/post-workout meals\nStraight-from-the-jar cravings\n\nWhy you’ll love it:\n\nSmooth & creamy texture\nRich dark chocolate flavor\nGood source of plant-based protein\nEnergy-boosting healthy fats\nGreat for fitness & healthy snacking",
      "price": 135,
      "mrp": 135,
      "weight": "400g",
      "textureVariants": [
        "Smooth",
        "Crunchy",
        "Crispy"
      ],
      "sizeVariants": [
        "400g",
        "500g",
        "900g"
      ],
      "variantPrices": {
        "Smooth-400g": {
          "basePrice": 129,
          "gstPercent": 5,
          "mrp": 135,
          "discountPercent": 0,
          "price": 135,
          "profit": 6
        },
        "Smooth-500g": {
          "basePrice": 161,
          "gstPercent": 5,
          "mrp": 169,
          "discountPercent": 0,
          "price": 169,
          "profit": 8
        },
        "Smooth-900g": {
          "basePrice": 290,
          "gstPercent": 5,
          "mrp": 305,
          "discountPercent": 0,
          "price": 305,
          "profit": 15
        },
        "Crunchy-400g": {
          "basePrice": 140,
          "gstPercent": 5,
          "mrp": 147,
          "discountPercent": 0,
          "price": 147,
          "profit": 7
        },
        "Crunchy-500g": {
          "basePrice": 175,
          "gstPercent": 5,
          "mrp": 184,
          "discountPercent": 0,
          "price": 184,
          "profit": 9
        },
        "Crunchy-900g": {
          "basePrice": 315,
          "gstPercent": 5,
          "mrp": 331,
          "discountPercent": 0,
          "price": 331,
          "profit": 16
        },
        "Crispy-400g": {
          "basePrice": 146,
          "gstPercent": 5,
          "mrp": 153,
          "discountPercent": 0,
          "price": 153,
          "profit": 7
        },
        "Crispy-500g": {
          "basePrice": 182,
          "gstPercent": 5,
          "mrp": 191,
          "discountPercent": 0,
          "price": 191,
          "profit": 9
        },
        "Crispy-900g": {
          "basePrice": 328,
          "gstPercent": 5,
          "mrp": 344,
          "discountPercent": 0,
          "price": 344,
          "profit": 16
        }
      },
      "gstPercent": 5,
      "profitMargin": 40,
      "discountPercent": 10,
      "variantBasePricePerKg": {
        "Smooth": 230,
        "Crunchy": 250,
        "Crispy": 260,
        "Dark Chocolate": 500,
        "Chocolate Crunchy": 500,
        "Natural": 521
      },
      "image": "https://i.ibb.co/psxqc3J/1-removebg-preview.png",
      "images": [
        "https://i.ibb.co/psxqc3J/1-removebg-preview.png",
        "https://i.ibb.co/SDG4SYSN/1.png"
      ],
      "emoji": "🥜",
      "badge": "Best Seller",
      "badgeType": "bestseller",
      "bgClass": "peanut-bg",
      "category": "peanut-butter",
      "features": [
        "High Protein",
        "No Palm Oil",
        "Vegan"
      ],
      "ingredients": "Roasted Peanuts (95%), Dark Cocoa Powder (4%), Salt (1%). No added sugar, no palm oil, no preservatives.",
      "keyBenefits": "Rich source of plant-based protein • Contains healthy monounsaturated fats • No palm oil or artificial preservatives • Antioxidant-rich dark cocoa • Suitable for pre/post-workout nutrition",
      "storageInfo": "Store in a cool, dry place away from direct sunlight. Keep lid tightly closed after opening. Best consumed within 3 months of opening. No refrigeration required.",
      "allergenInfo": "Contains Peanuts.",
      "visible": true,
      "bestSeller": true
    },
    {
      "id": "choco-pb",
      "name": "Chocolate Peanut Butter",
      "tagline": "Guilt-free chocolate indulgence.",
      "description": "Dark cocoa meets rich peanut butter for a treat you can feel good about. No refined sugar, no palm oil. Great as a spread, dip, or protein shake mix-in.",
      "price": 329,
      "mrp": 399,
      "weight": "500g",
      "textureVariants": [
        "Smooth",
        "Crunchy",
        "Natural"
      ],
      "sizeVariants": [
        "250g",
        "500g",
        "900g"
      ],
      "variantPrices": {
        "Smooth-250g": {
          "basePrice": 140,
          "gstPercent": 18,
          "mrp": 165,
          "discountPercent": 10,
          "price": 149,
          "profit": 25
        },
        "Smooth-500g": {
          "basePrice": 260,
          "gstPercent": 18,
          "mrp": 307,
          "discountPercent": 10,
          "price": 276,
          "profit": 50
        },
        "Smooth-900g": {
          "basePrice": 430,
          "gstPercent": 18,
          "mrp": 507,
          "discountPercent": 10,
          "price": 456,
          "profit": 80
        },
        "Crunchy-250g": {
          "basePrice": 145,
          "gstPercent": 18,
          "mrp": 171,
          "discountPercent": 10,
          "price": 154,
          "profit": 28
        },
        "Crunchy-500g": {
          "basePrice": 270,
          "gstPercent": 18,
          "mrp": 319,
          "discountPercent": 10,
          "price": 287,
          "profit": 55
        },
        "Crunchy-900g": {
          "basePrice": 450,
          "gstPercent": 18,
          "mrp": 531,
          "discountPercent": 10,
          "price": 478,
          "profit": 85
        },
        "Natural-250g": {
          "basePrice": 150,
          "gstPercent": 18,
          "mrp": 177,
          "discountPercent": 10,
          "price": 159,
          "profit": 30
        },
        "Natural-500g": {
          "basePrice": 280,
          "gstPercent": 18,
          "mrp": 330,
          "discountPercent": 10,
          "price": 297,
          "profit": 60
        },
        "Natural-900g": {
          "basePrice": 470,
          "gstPercent": 18,
          "mrp": 555,
          "discountPercent": 10,
          "price": 500,
          "profit": 90
        }
      },
      "badge": null,
      "badgeType": null,
      "bestSeller": true,
      "image": "",
      "emoji": "🍫",
      "bgClass": "choco-bg",
      "features": [
        "Dark Cocoa",
        "No Palm Oil",
        "High Protein",
        "No Refined Sugar"
      ],
      "ingredients": "Roasted Peanuts (93%), Dark Cocoa Powder (5%), Himalayan Pink Salt (2%). No refined sugar, no palm oil, no artificial flavours.",
      "storageInfo": "Store in a cool, dry place. Keep lid tightly closed after use. Consume within 3 months of opening. No refrigeration needed.",
      "keyBenefits": "High in plant-based protein • Rich dark chocolate flavour without refined sugar • No palm oil • Healthy fats for sustained energy • Great for smoothies and baking",
      "category": "peanut-butter",
      "visible": true
    },
    {
      "id": "rolled-oats",
      "name": "Rolled Oats",
      "tagline": "Wholesome oats, heart-healthy goodness.",
      "description": "Quick-cooking whole grain rolled oats. Naturally high in beta-glucan fibre which supports heart health. Ideal for porridge, overnight oats, granola bars, and baking.",
      "price": 199,
      "mrp": 249,
      "weight": "1kg",
      "textureVariants": [],
      "sizeVariants": [
        "500g",
        "1kg"
      ],
      "variantPrices": {
        "default-500g": {
          "basePrice": 90,
          "gstPercent": 5,
          "mrp": 95,
          "discountPercent": 5,
          "price": 90,
          "profit": 15
        },
        "default-1kg": {
          "basePrice": 170,
          "gstPercent": 5,
          "mrp": 179,
          "discountPercent": 5,
          "price": 170,
          "profit": 30
        }
      },
      "badge": "New",
      "badgeType": "new",
      "bestSeller": false,
      "image": "",
      "emoji": "🌾",
      "bgClass": "oat-bg",
      "features": [
        "Whole Grain",
        "High Fibre",
        "Heart Healthy",
        "No Preservatives"
      ],
      "ingredients": "100% Whole Grain Rolled Oats. No added sugar, no salt, no preservatives, no artificial flavours.",
      "storageInfo": "Store in a cool, dry, airtight container. Keep away from moisture. Best consumed within 12 months of manufacturing date once opened.",
      "keyBenefits": "High in beta-glucan fibre for heart health • Naturally gluten-free grain (check for cross-contamination) • Slow-release carbohydrates for sustained energy • Supports healthy cholesterol levels • Versatile for porridge, baking, and granola",
      "category": "oats",
      "visible": true
    },
    {
      "id": "crunchy-muesli",
      "name": "Crunchy Muesli",
      "tagline": "Your perfect power-packed breakfast.",
      "description": "A premium blend of rolled oats, mixed nuts, seeds, and real dried fruits. Loaded with fibre, healthy fats, and natural energy. No artificial flavours or added sugar.",
      "price": 349,
      "mrp": 429,
      "weight": "500g",
      "textureVariants": [],
      "sizeVariants": [
        "500g",
        "1kg"
      ],
      "variantPrices": {
        "default-500g": {
          "basePrice": 280,
          "gstPercent": 5,
          "mrp": 294,
          "discountPercent": 5,
          "price": 279,
          "profit": 55
        },
        "default-1kg": {
          "basePrice": 520,
          "gstPercent": 5,
          "mrp": 546,
          "discountPercent": 5,
          "price": 519,
          "profit": 100
        }
      },
      "badge": null,
      "badgeType": null,
      "bestSeller": false,
      "image": "",
      "emoji": "🥣",
      "bgClass": "muesli-bg",
      "features": [
        "Mixed Nuts",
        "Dried Fruits",
        "No Added Sugar",
        "High Fibre"
      ],
      "ingredients": "Rolled Oats (55%), Mixed Nuts (Almonds, Cashews, Walnuts) (18%), Dried Fruits (Raisins, Cranberries) (15%), Seeds (Sunflower, Pumpkin) (10%), Cinnamon (2%). No added sugar, no artificial flavours, no preservatives.",
      "storageInfo": "Store in a cool, dry place in an airtight container. Avoid humidity. Best consumed within 6 months of opening. Do not refrigerate.",
      "keyBenefits": "Loaded with dietary fibre for gut health • Natural sugars from real dried fruits only • Healthy fats from mixed nuts and seeds • Rich in vitamins and minerals • Ideal as a breakfast with milk or yoghurt",
      "category": "muesli",
      "visible": true
    }
  ],
  "hero": {
    "subtitle": "Welcome to Bunofeed",
    "title": "Companion in your",
    "titleHighlight": "Healthy Lifestyle",
    "description": "Fuel your body with nature's finest — real, healthy food products. No nasties. Just goodness.",
    "ctaText": "Shop Now",
    "ctaLink": "shop.html"
  },
  "brand": {
    "email": "bunofeedhelpdesk@gmail.com",
    "feedbackFormUrl": "https://docs.google.com/forms/d/e/1FAIpQLSejJAsyZq1snX9gEJr6CTpcVYwEopd34RsTf_pbYvgwz0WFDg/viewform?usp=header",
    "instagram": "https://www.instagram.com",
    "facebook": "https://www.facebook.com",
    "youtube": "https://www.youtube.com",
    "twitter": "https://www.x.com",
    "linkedin": "https://www.linkedin.com/in/akash-kumar-995739293"
  },
  "categories": [
    {
      "name": "Peanut Butter",
      "slug": "peanut-butter"
    },
    {
      "name": "Oats",
      "slug": "oats"
    },
    {
      "name": "Muesli",
      "slug": "muesli"
    },
    {
      "name": "Other",
      "slug": "other"
    }
  ]
};
